app.controller("insertUser", function ($scope, usersService, $rootScope, $location) {
    $scope.insertUser = function () {
        let message = confirm("Prénom: " + $scope.firstName + ", Nom: " + $scope.lastName + ", Email: " + $scope.email + "Voulez-vous créer cet utilisateur?")
        if (message) {
            $rootScope.loading = true;
            usersService.insertUser($scope.firstName, $scope.lastName, $scope.email, $scope.createdAt).then(function () {
                    $scope.insertMessage = "L'utilisateur a bien été créé.";
                    $rootScope.loading = false;
                }),
                function () {
                    $scope.errorMessage = "Données invalides. Veuillez réessayer";

                };
        };
    }
    //NB : There isn't any variable containing today's date since it's generated by the API

});